site_name: amorce
repo_url: https://github.com/gheleguen/amorce.git
edit_uri: -/edit/main/docs/

nav:
    - Introduction: index.md
    - Guide outil de maquettage: 2_maquettage/outils_maquettage.md
    - Templates: 3_templates/templates_doc.md
    - Licence: licence.md
    - Ax. Annexes: 
      - Conception outil de maquettage: 2_maquettage/notes_conception.md
        
theme:
    name: material
    palette:
      primary: yellow

plugins:
  - search

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
