site_name: amorce
repo_url: https://github.com/gheleguen/amorce.git
edit_uri: -/edit/main/docs/

nav:
    - Introduction: index.md
    - Fabrication de la toile d'amorce: 1_identification_profil/outils_toile_amorce.md
    - Guide outil de maquettage: 2_maquettage/outils_maquettage.md
    - Templates: 3_templates/templates_doc.md
    - Les boites empilables: Boites/fabriquer_boites.md
    - Licence: licence.md
    - Ax. Annexes: 
      - Conception outil de profilage: 1_identification_profil/notes_conception_toile_amorce.md
      - Conception outil de maquettage: 2_maquettage/notes_conception.md
        
theme:
    name: material
    palette:
      primary: yellow

plugins:
  - search

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
